### PR TITLE
Update guac-install.sh

### PR DESCRIPTION
**Pull request by berndhose**
Latest stable version of maven changed to 3.6.1
Full path for maven added to compile guac-client

### CODE REVIEW

**Comment by berndhose** [comment]
changed string rpmfusion to rpmfusion-free-release to make check for install work

**Comment by Zer0CoolX** [comment]
Thanks for the input. Did you re-test MySQL Connector 8.x to ensure it no longer has errors related to timezone as per Issue [#38](https://github.com/Zer0CoolX/guacamole-install-rhel/issues/38)?

From what I recall, I think the error was only present when using just MariaDB as the authentication AND during DST (IE: 8.x works for me half the year, but not the other half). 5.x does not have this issue.

**Comment by Zer0CoolX** [comment]
For now leaving MySQL connector @ 5.x version. If you have tested it with 8.x and it no longer has the issue from #38 we can update the default version number back to 8.x. Thanks

**Comment by berndhose** [comment]
Yesterday the SQL connector worked, today it doesn't anymore. Strange. I suggest staying on 5.x for the SQL connector.

**Pull request merged**
